services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
      - ./cert:/cert:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    environment:
      - UPTIME_KUMA_SSL_KEY=/cert/privkey.pem
      - UPTIME_KUMA_SSL_CERT=/cert/fullchain.pem
    restart: unless-stopped