services:
  watchtower:
    image: beatkind/watchtower
    container_name: watchtower
    secrets:
      - watchtower_secret
    restart: unless-stopped
    dns: 8.8.8.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Europe/Copenhagen
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "0 0 1 * * *"
      WATCHTOWER_NO_STARTUP_MESSAGE: false
      WATCHTOWER_NOTIFICATION_REPORT: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: watchtower@menzi.dk
      WATCHTOWER_NOTIFICATION_EMAIL_TO: alerts@menzi.dk
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: send.one.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: watchtower@menzi.dk
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "/run/secrets/watchtower_secret"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 120

secrets:
  watchtower_secret:
    file: watchtower_secret.txt
