services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/containers/homeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./cert:/ssl:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    healthcheck:
      test: curl -k https://localhost:8123 || exit 1