services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./cert:/cert:ro
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
      - HOMEPAGE_SSL_CERT=/cert/fullchain.pem
      - HOMEPAGE_SSL_KEY=/cert/privkey.pem
    restart: unless-stopped